// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5z5oT3p5w__fW8AydxRZmFEl2eRr9wyg',
    appId: '1:469399275043:web:5f2ff2d50d8dec77e65396',
    messagingSenderId: '469399275043',
    projectId: 'africakonamiad',
    authDomain: 'africakonamiad.firebaseapp.com',
    storageBucket: 'africakonamiad.appspot.com',
    measurementId: 'G-ZZ5C7J9JJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8HddQl2muwj2dcHE8RXlea6gkkLUsyvg',
    appId: '1:469399275043:android:15d66a75879983c8e65396',
    messagingSenderId: '469399275043',
    projectId: 'africakonamiad',
    storageBucket: 'africakonamiad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4WhIFJEitZY7H2KUSYPkypT8cgJLvc8U',
    appId: '1:469399275043:ios:b5318b7126fc0758e65396',
    messagingSenderId: '469399275043',
    projectId: 'africakonamiad',
    storageBucket: 'africakonamiad.appspot.com',
    iosClientId: '469399275043-tp2lpopl9q5djec22l26rqbqg5olbq1s.apps.googleusercontent.com',
    iosBundleId: 'com.konami.africa.konamiafricaad',
  );
}
